name: geocoder_buddy
description: Forward, Reverse geocoding and Search Address without any apikey.
version: 1.0.1
homepage: https://github.com/flutterbuddy1/geocoder_buddy
repository: https://github.com/flutterbuddy1/geocoder_buddy
issue_tracker: https://github.com/flutterbuddy1/geocoder_buddy/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dartdoc: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

